package com.moneymap.model;

import java.time.Instant;

/**
 * Single-use registration invite token for INVITE_ONLY mode (Section 01 §1.1 / §6.6).
 * Generated by an admin; default 7-day expiry; consumed on successful registration.
 */
public class InviteToken {
    private String id;
    private String token;           // random, high-entropy; appears in the invite URL
    private String createdByUserId;
    private Instant expiresAt;
    private String usedByUserId;    // set when consumed; a used token is never valid again
    private Instant usedAt;
    private Instant createdAt;

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }
    public String getCreatedByUserId() { return createdByUserId; }
    public void setCreatedByUserId(String createdByUserId) { this.createdByUserId = createdByUserId; }
    public Instant getExpiresAt() { return expiresAt; }
    public void setExpiresAt(Instant expiresAt) { this.expiresAt = expiresAt; }
    public String getUsedByUserId() { return usedByUserId; }
    public void setUsedByUserId(String usedByUserId) { this.usedByUserId = usedByUserId; }
    public Instant getUsedAt() { return usedAt; }
    public void setUsedAt(Instant usedAt) { this.usedAt = usedAt; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
