package com.moneymap.model.expense;

import com.moneymap.model.asset.OwnedRecord;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * A single expense or income transaction. Standalone module — isolated from the
 * Assets/Liabilities schema, no changes to existing net-worth-bearing modules.
 */
public class ExpenseEntry extends OwnedRecord {

    /** One of the PRESET_CATEGORIES, or any free-text value when the family defines its own. */
    private String category;
    private BigDecimal amount;
    private LocalDate date;
    private String note;
    /** EXPENSE (outflow) or INCOME (credit, e.g. salary) */
    private String direction;
    /** When direction=INCOME and the credit is a salary, the originating SalaryProfile id. */
    private String linkedSalaryProfileId;
    /** Optional link to the account the money moved through (e.g. a savings account id). */
    private String linkedAccountId;
    private String currency = "INR";
    /** Set when this entry was auto-generated by a RecurringRule. */
    private String recurringRuleId;

    public static final java.util.List<String> PRESET_CATEGORIES = java.util.List.of(
            "Groceries", "Rent", "Utilities", "Transport", "Dining", "Healthcare",
            "Entertainment", "Other");

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }
    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }
    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }
    public String getNote() { return note; }
    public void setNote(String note) { this.note = note; }
    public String getDirection() { return direction; }
    public void setDirection(String direction) { this.direction = direction; }
    public String getLinkedSalaryProfileId() { return linkedSalaryProfileId; }
    public void setLinkedSalaryProfileId(String linkedSalaryProfileId) { this.linkedSalaryProfileId = linkedSalaryProfileId; }
    public String getLinkedAccountId() { return linkedAccountId; }
    public void setLinkedAccountId(String linkedAccountId) { this.linkedAccountId = linkedAccountId; }
    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }
    public String getRecurringRuleId() { return recurringRuleId; }
    public void setRecurringRuleId(String recurringRuleId) { this.recurringRuleId = recurringRuleId; }
}
